package org.wikicleta.helpers;

import java.util.ListResourceBundle;

public class Resources_esMx extends ListResourceBundle
{

    private static final Object[][] OBJECTS = new Object[][] {
                                                              { "CenturyPattern", "%n %u" },
                                                              { "CenturyFuturePrefix", "dentro de " },
                                                              { "CenturyFutureSuffix", "" },
                                                              { "CenturyPastPrefix", "hace " },
                                                              { "CenturyPastSuffix", "" },
                                                              { "CenturySingularName", "siglo" },
                                                              { "CenturyPluralName", "siglos" },
                                                              { "DayPattern", "%n %u" },
                                                              { "DayFuturePrefix", "dentro de " },
                                                              { "DayFutureSuffix", "" },
                                                              { "DayPastPrefix", "hace " },
                                                              { "DayPastSuffix", "" },
                                                              { "DaySingularName", "d’a " },
                                                              { "DayPluralName", "d’as" },
                                                              { "DecadePattern", "%n %u" },
                                                              { "DecadeFuturePrefix", "dentro de " },
                                                              { "DecadeFutureSuffix", "" },
                                                              { "DecadePastPrefix", "hace " },
                                                              { "DecadePastSuffix", "" },
                                                              { "DecadeSingularName", "decenio" },
                                                              { "DecadePluralName", "decenios" },
                                                              { "HourPattern", "%n %u" },
                                                              { "HourFuturePrefix", "dentro de " },
                                                              { "HourFutureSuffix", "" },
                                                              { "HourPastPrefix", "hace " },
                                                              { "HourPastSuffix", "" },
                                                              { "HourSingularName", "hora" },
                                                              { "HourPluralName", "horas" },
                                                              { "JustNowPattern", "%u" },
                                                              { "JustNowFuturePrefix", "" },
                                                              { "JustNowFutureSuffix", "hace un instante" },
                                                              { "JustNowPastPrefix", "hace unos instantes" },
                                                              { "JustNowPastSuffix", "" },
                                                              { "JustNowSingularName", "" },
                                                              { "JustNowPluralName", "" },
                                                              { "MillenniumPattern", "%n %u" },
                                                              { "MillenniumFuturePrefix", "dentro de " },
                                                              { "MillenniumFutureSuffix", "" },
                                                              { "MillenniumPastPrefix", "hace " },
                                                              { "MillenniumPastSuffix", "" },
                                                              { "MillenniumSingularName", "milenario" },
                                                              { "MillenniumPluralName", "milenarios" },
                                                              { "MillisecondPattern", "%n %u" },
                                                              { "MillisecondFuturePrefix", "dentro de " },
                                                              { "MillisecondFutureSuffix", "" },
                                                              { "MillisecondPastPrefix", "hace " },
                                                              { "MillisecondPastSuffix", "" },
                                                              { "MillisecondSingularName", "milisegundo" },
                                                              { "MillisecondPluralName", "milisegundo" },
                                                              { "MinutePattern", "%n %u" },
                                                              { "MinuteFuturePrefix", "dentro de " },
                                                              { "MinuteFutureSuffix", "" },
                                                              { "MinutePastPrefix", "hace " },
                                                              { "MinutePastSuffix", "" },
                                                              { "MinuteSingularName", "minuto" },
                                                              { "MinutePluralName", "minutos" },
                                                              { "MonthPattern", "%n %u" },
                                                              { "MonthFuturePrefix", "dentro de " },
                                                              { "MonthFutureSuffix", "" },
                                                              { "MonthPastPrefix", "hace " },
                                                              { "MonthPastSuffix", "" },
                                                              { "MonthSingularName", "mes" },
                                                              { "MonthPluralName", "meses" },
                                                              { "SecondPattern", "%n %u" },
                                                              { "SecondFuturePrefix", "dentro de " },
                                                              { "SecondFutureSuffix", "" },
                                                              { "SecondPastPrefix", "hace " },
                                                              { "SecondPastSuffix", "" },
                                                              { "SecondSingularName", "segundo" },
                                                              { "SecondPluralName", "segundos" },
                                                              { "WeekPattern", "%n %u" },
                                                              { "WeekFuturePrefix", "dentro de " },
                                                              { "WeekFutureSuffix", "" },
                                                              { "WeekPastPrefix", "hace " },
                                                              { "WeekPastSuffix", "" },
                                                              { "WeekSingularName", "semana" },
                                                              { "WeekPluralName", "semanas" },
                                                              { "YearPattern", "%n %u" },
                                                              { "YearFuturePrefix", "dentro de " },
                                                              { "YearFutureSuffix", "" },
                                                              { "YearPastPrefix", "hace " },
                                                              { "YearPastSuffix", "" },
                                                              { "YearSingularName", "a–o" },
                                                              { "YearPluralName", "a–os" },
                                                              { "AbstractTimeUnitPattern", "" },
                                                              { "AbstractTimeUnitFuturePrefix", "" },
                                                              { "AbstractTimeUnitFutureSuffix", "" },
                                                              { "AbstractTimeUnitPastPrefix", "" },
                                                              { "AbstractTimeUnitPastSuffix", "" },
                                                              { "AbstractTimeUnitSingularName", "" },
                                                              { "AbstractTimeUnitPluralName", "" } };

    @Override
    protected Object[][] getContents()
    {
        return OBJECTS;
    }
}